### ISSUE TITLE
Symbolic expansion broken in Newton notebook 1.6

### ISSUE THREAD

**Issue by dpsanders** [mitmath/18S191#115]
@fonsp: Symbolic expansion isn't working on the published version. Maybe it just needs regenerating with a current version of Symbolics.jl?

**Comment by fonsp** [comment]
@dpsanders Do you mean that we are using a version of Symbolics where it doesn't work, but it has been fixed in a recent version?

**Comment by fonsp** [comment]
The issue is that `expand` has no effect

<img width="467" alt="image" src="https://github.com/user-attachments/assets/6b3d5b11-598d-4c73-8661-608b1f4fb909">


in https://computationalthinking.mit.edu/Fall24/images_abstractions/newton_method/
