### ISSUE TITLE
Link on readme is to Spring21 instead of latest

### ISSUE THREAD

**Issue by fayolle** [mitmath/18S191#138]
The link at the end of the readme file 
https://github.com/mitmath/computational-thinking/blob/578736f39c6eeb388ff5c51f9f28f0b8d8f29670/README.md
points to the Spring21 version instead of the latest version. 

```
# Go to [computationalthinking.mit.edu](https://computationalthinking.mit.edu/Spring21/) to learn more!
```
should be 
```
# Go to [computationalthinking.mit.edu](https://computationalthinking.mit.edu/) to learn more!
```

**Comment by fonsp** [comment]
Thanks!
