### ISSUE TITLE
http -> https and URL update

### ISSUE THREAD

**Issue by ViralBShah** [mitmath/18S191#21]
Redirect the http to https for the computationalthinking.mit.edu URL. Or click "Enforce HTTPS" in settings.

Also, update the URL for the class on the repo. 

cc @christopher-dG

**Comment by christopher-dG** [comment]
@shashi took care of the checkbox, and the URLs too I think (although there's a typo in website-docs.md: computationalthinking.mit.edut/Fall20 which should be https://computationalthinking.mit.edu/Fall20)

**Comment by christopher-dG** [comment]
The URL in the repo settings could be updated though.
