### ISSUE TITLE
website: code blocks in installation instructions

### ISSUE THREAD

**Issue by zmoon** [mitmath/18S191#22]
This page: https://computationalthinking.mit.edu/Fall20/installation/

Looks fine [on GitHub](https://github.com/mitmath/18S191/blob/master/website/installation.md) but on the website literal HTML entities are shown.

For example:

![image](https://user-images.githubusercontent.com/15079414/93000220-dcb0e700-f4f4-11ea-8fe9-9fde1b0d9063.png)

**Comment by dpsanders** [comment]
Oops, thanks for the report. We'll look into fixing this.

**Comment by zmoon** [comment]
Seems like a broader current Julia Markdown machinery issue? Even seeing on the Julia install page right now: <https://julialang.org/downloads/platform/>:

![image](https://user-images.githubusercontent.com/15079414/93029735-66db7700-f5eb-11ea-9aa5-bdb94117abfb.png)

**Comment by fonsp** [comment]
The Julia install page is written in Franklink - the Franklin issue you linked is probably the cause

**Comment by fonsp** [comment]
Fixed!
