### ISSUE TITLE
website: hw download links

### ISSUE THREAD

**Issue by zmoon** [mitmath/18S191#23]
I think raw versions of the hw links need to be used if you want people to be able to indeed download the files by right clicking.

e.g.,  
<https://github.com/mitmath/18S191/raw/master/homework/homework0/hw0.jl>
or
<https://raw.githubusercontent.com/mitmath/18S191/master/homework/homework0/hw0.jl>
for hw0, instead of 
<https://github.com/mitmath/18S191/blob/master/homework/homework0/hw0.jl>

**Comment by zmoon** [comment]
But I guess if you are just putting the link in Pluto it doesn't matter.

**Comment by fonsp** [comment]
Do you feel like writing this yourself in a PR?
