### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by sbhhdp** [mitmath/18S191#25]
The [link](https://github.com/mitmath/18S191/blob/master/course-materials.md) that takes one to the summary of the course materials seems to be not working

**Comment by fonsp** [comment]
Where is the link?

**Comment by sbhhdp** [comment]
> Where is the link?

On this page (https://github.com/mitmath/18S191 ) under course materials section ....the first one

**Comment by fonsp** [comment]
Thanks!
