### ISSUE TITLE
Scrolling in the sidebar is broken

### ISSUE THREAD

**Issue by anujLabVIEW** [mitmath/18S191#26]
I cannot scroll on the lefthand sidebar. So `Homework 2` isn't visible until I go fullscreen or use a device with a portrait mode.

**Normal screen**
![image](https://user-images.githubusercontent.com/35781438/93048571-d188c300-f67c-11ea-8a26-c4c537aa29eb.png)

**Fullscreen**
![image](https://user-images.githubusercontent.com/35781438/93048640-f54c0900-f67c-11ea-9d32-379805388144.png)

**Comment by fonsp** [comment]
Thanks!
