### ISSUE TITLE
week4/02-covid_data.jl Julia-1.5.2: ERROR: plot not defined

### ISSUE THREAD

**Issue by sck** [mitmath/18S191#42]
I get this error when i try to run 02-covid_data.jl in Pluto.  I thought I was just missing a Pkg.add() but it seems plot() used to be available in earlier versions of Julia, but has been deprecated for quite a while, and I am not sure where the plot() should be coming from.  (In the course website you write that you are using Julia 1.5.1.)

**Comment by dpsanders** [comment]
You didn't send the error.

`plot()` is from the Plots.jl package and is not deprecated.

**Comment by sck** [comment]
![error](https://user-images.githubusercontent.com/58959/94967969-5fc7ca80-0500-11eb-88cd-caf036cb5270.png)

Error message is in the title of this issue, but here is a screenshot.

When i do `Pkg.add('Plots')` `using Plots` I get `Multiple definitions for Plots` 

![plots](https://user-images.githubusercontent.com/58959/94968441-352a4180-0501-11eb-9e7d-1427257b98af.png)

**Comment by dpsanders** [comment]
That seems strange. Delete the new definitions, close the notebook, stop it wirh the x next to its name and open it again maybe?

**Comment by dpsanders** [comment]
There's no message from the previous cell with `using Plots`?

**Comment by fonsp** [comment]
This should fix it:
https://github.com/mitmath/18S191/commit/7409e78510383c1d8ffda7c0666a0734e54ee8c2

Try loading the notebook again from the new source:
https://github.com/mitmath/18S191/blob/master/lecture_notebooks/week4/02-covid_data.jl

Does that work?

**Comment by MteaHubHug** [comment]
I have a little problem here :
![image](https://user-images.githubusercontent.com/73033883/115262968-4fdaa580-a135-11eb-82f0-66fdd7afe04d.png)
