### ISSUE TITLE
add link to github

### ISSUE THREAD

**Issue by fonsp** [mitmath/18S191#5]
Which GitHub do you mean? The website?

**Comment by tasneemkoushar** [comment]
The issue is not clear to me! Can you tell us more about the issue?

**Comment by fonsp** [comment]
I'm sorry that was a useless issue 😬

I meant that the web pages should like back to GitHub, inviting readers to contribute a fix or open an issue if they find something.

**Comment by dpsanders** [comment]
Yes definitely a good idea!

**Comment by fonsp** [comment]
@shashi is this trivial for you to do? Otherwise I will look into it myself

**Comment by shashi** [comment]
Like edit on github link on each page??

I don't know how to do that off the top of my head, but I'm sure it's not that hard!

**Comment by tasneemkoushar** [comment]
I will do it, kindly assign this issue to me. Thank you

**Comment by dpsanders** [comment]
Fixed by #11
