### ISSUE TITLE
Time stamps do not show up in the embedded videos

### ISSUE THREAD

**Issue by logankilpatrick** [mitmath/18S191#62]
See here: https://computationalthinking.mit.edu/Fall20/lecture26/#what_is_a_discrete_fourier_transform and then look at the difference on YouTube

**Comment by fonsp** [comment]
It can't be done in the embed, so we would have to implement the functionality ourselves (and scrape timestamps from the description)

**Comment by logankilpatrick** [comment]
Okay, then let's include this functionality in #65 whenever I can get that working.
