### ISSUE TITLE
License

### ISSUE THREAD

**Issue by greimel** [mitmath/18S191#69]
Hi,

I am preparing a course based on Pluto notebooks and I would like to base some of the material on notebooks from this repo. Since there is no license in this repository, would you mind clarifying under which conditions I can reuse some of the material?

In particular, I would like to use your install instructions, the hw0.jl and the notebook on basic syntax.

Best,
Fabian

**Comment by fonsp** [comment]
You can use the install instructions (including video) and hw0 yourself without crediting us. I am not sure what you mean with _basic syntax_, but you can take useful technical bits from our notebooks and use them for your own use without crediting us. Is this what you meant?

If you would like to reuse actual course material (videos, exercises, text), then that's something we have to discuss with everyone else, but you can always _link_ to our web page.

**Comment by dpsanders** [comment]
We do definitely need to add an actual license though. I would usually go with MIT for the code and a creative commons license for the text. But as @fonsp says, we will need to discuss that.

**Comment by greimel** [comment]
Thanks for your answers. I was talking about this notebook https://github.com/mitmath/18S191/blob/Fall20/lecture_notebooks/Basic%20Julia%20syntax.jl

Congrats for the nice course, btw. It will surely serve as a source of inspiration for many teachers!
