### ISSUE TITLE
The invite link for Discord is expired

### ISSUE THREAD

**Issue by amiltonwong** [mitmath/18S191#9]
Hi, all,

The invite link for Discord is expired. Could you help to create a new one?

THX!

**Comment by fonsp** [comment]
Thanks

**Comment by dovinmu** [comment]
The link is expired again, @fonsp could you update it again?

**Comment by fonsp** [comment]
Haha I just saw that we have 1300 members...

**Comment by fonsp** [comment]
https://discord.gg/Z5qnVf8

**Comment by fonsp** [comment]
Ah discord reused the old invite link, so we don't need to update the page - nice!

**Comment by SanJJ1** [comment]
Can someone just generate a permanent link so we don't have to keep using new ones ?

**Comment by dovinmu** [comment]
I just noticed that Discord will tell me the link is expired if I open it in Firefox, but not in Chrome. It's possible it was getting tripped up by some of my privacy extensions

**Comment by fonsp** [comment]
This one is permanent
